dockerboard/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from .views import ContainerList, ContainerView, ImageList


app_name = 'api'

urlpatterns = [
    path(r'containers/', ContainerList.as_view()),
    path(r'containers/<int:pk>/', ContainerView.as_view()),
    path(r'images/', ImageList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

dockerboard/dashboard/urls.py
from django.conf.urls import url
from . import views


app_name = 'dashboad'

urlpatterns = [
    url('', views.index, name='index'),
]

dockerboard/dockerboard/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$', include('dashboard.urls', namespace='dashboard')),
    url(r'^api/', include('api.urls', namespace='api')),
] + static(settings.STATIC_URL)

dockerboard/images/urls.py
from django.conf.urls import url
from . import views


app_name = 'images'

urlpatterns = [
    url(r'^list.html$', views.list, name='list'),
    url(r'^(?P<image_id>.+)/details.html$', views.details, name='details'),
]

dockerboard/settings/urls.py
from django.conf.urls import url
from . import views


app_name = 'settings'

urlpatterns = [
    url('', views.index, name='index'),
]

dockerboard/api/models.py
from django.db import models

# Create your models here.

dockerboard/api/views.py
from django.http import HttpResponse, HttpResponseNotModified
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import serializers

from .client import DockerClient
from .serializers import ContainerSerializer, ImageSerializer


class ContainerList(APIView):
    """
    List all containers or add a new one.
    """
    def get(self, request, format=None):
        client = DockerClient()
        containers = client.list_containers(all=True)
        serializer = ContainerSerializer(containers, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = SnippetSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ContainerView(APIView):
    """
    Retrieve, update or delete a container instance.
    """
    def get(self, request, pk, format=None):
        container = None
        serializer = ContainerSerializer(snippet)
        return Response(serializer.data)


class ImageList(APIView):
    """
    List all images or add a new one.
    """
    def get(self, request, format=None):
        client = DockerClient()
        serializer = ImageSerializer(client.list_images(), many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = SnippetSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


def list(request):
    client = DockerizeClient()
    containers = client.containers(all=True)
    context = dict(
        containers=containers,
    )
    return render(request, 'containers/list.html', context)


def details(request, container_id):
    client = DockerizeClient()
    context = dict(
        container=client.get_container(container_id)
    )
    return render(request, 'containers/details.html', context)


def start(request, container_id):
    task = app.send_task('start_container', [container_id,])
    result = task.get(timeout=60)
    return HttpResponse() if result else HttpResponseNotModified()


def restart(request, container_id):
    task = app.send_task('restart_container', [container_id,])
    result = task.get(timeout=60)
    return HttpResponse() if result else HttpResponseNotModified()


def stop(request, container_id):
    task = app.send_task('stop_container', [container_id,])
    result = task.get(timeout=60)
    return HttpResponse() if result else HttpResponseNotModified()

dockerboard/common/views.py
from django.shortcuts import render

# Create your views here.

dockerboard/containers/views.py
from django.http import HttpResponse, HttpResponseNotModified
from django.shortcuts import render
from dockerize.client import DockerizeClient
from dockerize.tasks import app


def list(request):
    client = DockerizeClient()
    containers = client.containers(all=True)
    context = dict(
        containers=containers,
    )
    return render(request, 'containers/list.html', context)


def details(request, container_id):
    client = DockerizeClient()
    context = dict(
        container=client.get_container(container_id)
    )
    return render(request, 'containers/details.html', context)


def start(request, container_id):
    task = app.send_task('start_container', [container_id,])
    result = task.get(timeout=60)
    return HttpResponse() if result else HttpResponseNotModified()


def restart(request, container_id):
    task = app.send_task('restart_container', [container_id,])
    result = task.get(timeout=60)
    return HttpResponse() if result else HttpResponseNotModified()


def stop(request, container_id):
    task = app.send_task('stop_container', [container_id,])
    result = task.get(timeout=60)
    return HttpResponse() if result else HttpResponseNotModified()

dockerboard/dashboard/views.py
from django.shortcuts import render


def index(request):
    context = dict()
    return render(request, 'dashboard/index.html', context)

dockerboard/images/views.py
from django.shortcuts import render


def list(request):
    context = dict(
        images=client.images(),
    )
    return render(request, 'images/list.html', context)


def details(request, image_id):
    context = dict(
        image=client.get_image(image_id),
    )
    return render(request, 'images/details.html', context)

dockerboard/api/templates/containers/details.html
{% extends 'layout.html' %}
{% load prettify %}

{% block script %}
    $('.accordion').accordion({
        heightStyle: "content"
    });
{% endblock %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-lg-6">
            <h2>{{ container.name }} ({{ container.short_id }})</h2>
        </div>
        <div class="col-lg-6">
            <div class="float-right">
                <span class="btn btn-outline-success">
                    {{ container.status }}
                </span>
            </div>
        </div>
    </div>

    <div class="row">
        {{ container.image }}</li>
        {{ container.labels }}</li>
    </div>

    <div class="row">
        <div class="accordion col-lg-12">
            {% for key, values in container.attrs.items %}
            <h3>{{ key }}</h3>
            <div><p><pre>{{ values | pretty_yaml }}</pre></p></div>
            {% endfor %}
        </div>
    </div>

</div>
{% endblock %}

dockerboard/api/templates/containers/list.html
{% extends 'layout.html' %}

{% block script %}

    toggle_checkable = function(element) {
        $(element).toggleClass("btn-primary");
        $(element).toggleClass("btn-outline-primary");
        $(element).toggleClass("checked");
    }

    check_checkable = function(element) {
        $(element).addClass("btn-primary");
        $(element).removeClass("btn-outline-primary");
        $(element).addClass("checked");
    }

    uncheck_checkable = function(element) {
        $(element).removeClass("btn-primary");
        $(element).addClass("btn-outline-primary");
        $(element).removeClass("checked");
    }

    $(".button-checkable").click(function() {
        toggle_checkable(this);
    });

    $(".containers .dropdown-menu a").click(function() {
        var url = $(this).attr('data-url');
        var href = $(this).attr('href');
        if(href == '#') {
            $.get(url, function(data) {
                console.log(url);
                location.reload();
            });
        }
    });

    $(".button-bulk-action .dropdown-menu a").click(function() {
        var action = $(this).attr('data-action');
        if(action == 'select-all') {
            $(".button-checkable").each(function() {
                check_checkable(this);
            });
        }
        if(action == 'deselect-all') {
            $(".button-checkable").each(function() {
                uncheck_checkable(this);
            });
        }
    });

{% endblock %}

{% block content %}
<div class="container">

    <div class="row mb-3 mt-3">

        <div class="col-md-4">
            <div class="btn-group btn-block button-bulk-action">
                <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Bull action
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#" data-action="select-all">Select all</a>
                    <a class="dropdown-item" href="#" data-action="deselect-all">Deselect all</a>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <span class="btn btn-block btn-secondary">
                <b>Image</b>
            </span>
        </div>

        <div class="col-md-4">
            <span class="btn btn-block btn-secondary">
                <b>Status</b>
            </span>
        </div>

    </div>

    {% for container in containers %}
    <div class="row mb-2 containers">
        <div class="col-md-4">

            <div class="btn-group btn-block">
                <button class="btn btn-block btn-outline-primary button-checkable" type="button">
                    {{ container.name }}
                </button>
                <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu">
                <a class="dropdown-item" href="#" data-url="{% url 'containers:start' container.id %}" class="{% if container.state == 'running' %}disable{% endif %}">Start</a>
                    <a class="dropdown-item" href="#" data-url="{% url 'containers:restart' container.id %}">Restart</a>
                    <a class="dropdown-item" href="#" data-url="{% url 'containers:stop' container.id %}">Stop</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'containers:details' container.id %}">Details</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <a href="{% url 'images:details' container.image.id %}" class="btn btn-block btn-outline-secondary">
                {{ container.image.name }}
            </a>
        </div>
        <div class="col-md-4">
            <span class="btn btn-block 
                {% if container.status == 'running' %}btn-outline-success{% endif %}
                {% if container.status == 'exited' %}btn-outline-danger{% endif %}
                {% if container.status == 'created' %}btn-outline-warning{% endif %}
            ">
                {{ container.status }}
            </span>
        </div>
    </div>
    {% endfor %}

</div>
{% endblock %}

dockerboard/dashboard/templates/dashboard/index.html
{% extends 'layout.html' %}

{% block script %}

var ctx = document.getElementById('container-chart-line').getContext('2d');
var chart_line = new Chart(ctx, {
  type: 'line',
  data: {
    labels: [1500,1600,1700,1750,1800,1850,1900,1950,1999,2050],
    datasets: [{ 
        data: [86,114,106,106,107,111,133,221,783,2478],
        label: "Africa",
        borderColor: "#3e95cd",
        fill: false
      }, { 
        data: [6,3,2,2,7,26,82,172,312,433],
        label: "North America",
        borderColor: "#c45850",
        fill: false
      }
    ]
  }
});

var data = {
    labels: ["running", "not running"],
      datasets: [
        {
            fill: true,
            backgroundColor: [
                'green',
                'red'],
            data: [5, 95],
            borderColor: ['black', 'black'],
            borderWidth: [2,2]
        }
    ]
};

var options = {
    rotation: -0.7 * Math.PI
};

var ctx = document.getElementById('container-chart-pie').getContext('2d');
var chart_pie = new Chart(ctx, {
     type: 'pie',
    data: data,
    options: options
});

{% endblock %}

{% block content %}
<div class="container">

    <div class="row">
        <h2>Containers</h2>
    </div>

    <div class="row">
        <div class="col-md-8">
            <canvas id="container-chart-line" style="height: 200px; width: 100%;"><canvas>
        </div>
        <div class="col-md-4">
            <canvas id="container-chart-pie" style="height: 200px; width: 100%;"><canvas>
        </div>
    </div>

</div>
{% endblock %}

dockerboard/images/templates/images/details.html
{% extends 'layout.html' %}
{% load prettify %}

{% block script %}
    $('.accordion').accordion({
        heightStyle: "content"
    });
{% endblock %}

{% block content %}
<div class="container">

    <div class="row">
        <h2>{{ image }}</h2>
    </div>
    
    <div class="row">
        <div class="accordion col-lg-12">
            {% for key, values in image.attrs.items %}
            <h3>{{ key }}</h3>
            <div><p><pre>{{ values | pretty_yaml }}</pre></p></div>
            {% endfor %}
        </div>
    </div>

</div>
{% endblock %}

dockerboard/images/templates/images/list.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">

    <div class="row">
        <h2>Images</h2>
    </div>

    <div class="row">
        <ul>
        {% for image in images %}
            <li>{{ image }}</li>
        {% endfor %}
        </ul>
    </div>

</div>
{% endblock %}

dockerboard/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>

        <title>Dockerboard</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha256-YLGeXaapI0/5IgZopewRJcFXomhRMlYYjugPLSyNjTY=" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" integrity="sha256-rByPlHULObEjJ6XQxW/flG2r+22R5dKiAoef+aXWfik=" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.theme.min.css" integrity="sha256-AjyoyaRtnGVTywKH/Isxxu5PXI0s4CcE0BzPAX83Ppc=" crossorigin="anonymous" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha256-KM512VNnjElC30ehFwehXjx1YCHPiQkOPmqnrWtpccM=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha256-fzFFyH01cBVPYzl16KT40wqjhgPtq6FFUB6ckN2+GGw=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js" integrity="sha256-xKeoJ50pzbUGkpQxDYHD7o7hxe0LaOGeguUidbq6vis=" crossorigin="anonymous"></script>

        <style type="text/css">
            .loading-modal {
                display:    none;
                position:   fixed;
                z-index:    1000;
                top:        0;
                left:       0;
                height:     100%;
                width:      100%;
                background: rgba( 255, 255, 255, .8 ) 
                            url('{% static "loader.gif" %}') 
                            50% 50% 
                            no-repeat;
            }
            body.loading .loading-modal {
                overflow: hidden;   
            }
            body.loading .loading-modal {
                display: block;
            }
        </style>

    </head>
    <body style="padding-top: 4rem;">

        <main role="main">

            {% block content %}
            {% endblock %}

            <footer class="container mt-2">
                <p>
                    <a href="#" class="btn btn-outline-dark">Back to top</a>
                </p>
            </footer>

            <div class="loading-modal"></div>

        </main>

        <script type="text/javascript">

            $body = $("body");

            $(document).on({
                ajaxStart: function() { 
                    $body.addClass("loading");
                },
                ajaxStop: function() {
                    $body.removeClass("loading");
                }
            });

            $(document).ready(function() {
                {% block script %}
                {% endblock %}
            });

        </script>

    </body>
</html>